# Generated by Django 2.1.4 on 2019-01-14 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artistID', models.AutoField(primary_key=True, serialize=False)),
                ('fullName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('factID', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('author', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('songID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('sArtistID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facts.Artist')),
            ],
        ),
        migrations.AddField(
            model_name='fact',
            name='fSongID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facts.Song'),
        ),
    ]
